repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-json
        types: [text]
        files: \.(json|ipynb)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff
        name: ruff (isort jupyter)
        args: [--select, I, --fix]
        types_or: [ jupyter ]
      - id: ruff-format
        types_or: [ python, jupyter ]
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.4.0
    hooks:
      - id: biome-format
